theme: jekyll-theme-minimal
title: CUDA - 10 tutoriali dla początkujących
description: Podstawy programowania równoległego z użyciem CUDA
author: Natan Jarzyński, Mikołaj Królak, Marek Kowalik

# Does not affect the theme, but can be used in your templates
blog1_title: Ustawienie środowiska CUDA na Windowsie i Linuxie
blog1_url: /blog1
blog2_title: Prosty benchmark GPU
blog2_url: /blog2
blog3_title: Pisanie funkcji na GPU
blog3_url: /blog3