theme: jekyll-theme-minimal
title: CUDA - 10 tutoriali dla początkujących
description: Podstawy programowania równoległego z użyciem CUDA
author: Natan Jarzyński, Mikołaj Królak, Marek Kowalik


blog1_title: Strona główna
blog1_url: /blog1